name: Build and Run .NET WebApp

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # A cada hora

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar pacotes
        run: dotnet restore github4women/github4women.csproj

      - name: Compilar aplicação
        run: dotnet build github4women/github4women.csproj --no-restore

