steps:
  - name: Checkout do código
    uses: actions/checkout@v3

  - name: Instalar .NET
    uses: actions/setup-dotnet@v3
    with:
      dotnet-version: 7.0.x

  - name: Restaurar dependências
    run: dotnet restore github4women/github4women.csproj

  - name: Buildar o projeto
    run: dotnet build github4women/github4women.csproj --no-restore

  - name: Rodar o projeto
    run: dotnet run --project github4women/github4women.csproj
